import "@/styles/globals.css";

import type { Metadata } from "next";
import { Archivo } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";
import Link from "next/link";
import { cn } from "@/lib/utils";
import { UserMenu } from "./_components/UserMenu";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
	title: "Create T3 App",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const archivo = Archivo({
	subsets: ["latin"],
});

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="en" className={`${archivo.className}`}>
			<body>
				<TRPCReactProvider>
					<SessionProvider>
						<div className={cn("relative min-h-screen")}>
							<div className="flex w-full items-center justify-between border-black border-y-4 py-4 pr-4 pl-1">
								<Link
									href="/"
									className="w-fit font-bold text-3xl hover:text-main hover:underline sm:text-5xl"
								>
									Cookable
								</Link>
								<UserMenu />
							</div>
							{children}
							<div className="absolute right-0 bottom-0 left-0 border-t-2 bg-white py-2 text-center text-base">
								Made with 💙 in Stratford
							</div>
						</div>
						<Toaster />
					</SessionProvider>
				</TRPCReactProvider>
			</body>
		</html>
	);
}
